sudo: false

# version automatically picked up from .ruby-version
language: ruby
cache: bundler

notifications:
    email: false

before_install:
  - nvm install 12.19.0 --reinstall-packages-from=node
  - node -v
  - gem update --system
  - gem install bundler jekyll

before_script:
  - chmod +x ./bin/setup
  - ./bin/setup
  - bundle exec jekyll build

script: bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --ignore-urls="feed.xml" --allow-missing-href=true --ignore-status-codes=403 --enforce-https=false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - LC_ALL=en_US.UTF-8
    - JEKYLL_ENV=production
