version: 2.1

executors:
  docker_executor:
    docker:
      - image: circleci/ruby:2.7.1-buster-node

jobs:
  setup:
    executor: docker_executor
    steps:
      - checkout
      - run:
          name: Set up environment
          command: ./bin/setup
  test:
    executor: docker_executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            bundle exec jekyll build
            rm -R ./_site/node_modules
            bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --check-opengraph --url-ignore "feed.xml"

workflows:
  version: 2.1
  test_all:
    jobs:
      - setup
      - test:
          requires:
          - setup
